name: BuildNewCommits

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  prepare:
    name: Prepare Matrix
    runs-on: ubuntu-latest
        
    outputs:
      countries: ${{ steps.load_countries.outputs.countries }}
      
    steps:
      - name: Install BC Container Helper
        shell: pwsh   
        run: Install-Module bccontainerhelper -force

      - name: Check out the repository to the runner
        uses: actions/checkout@v4.1.2
        with:
          ref: master
      
      - name: Load Countries
        id: load_countries
        shell: pwsh       
        run: ./scripts/GetAllCountries.ps1

      - name: ShowOutput      
        shell: pwsh       
        run: Write-Host '${{ steps.load_countries.outputs.countries }}'
        
  buildCommits:
    needs: prepare
    name: Build Commits
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare.outputs.countries) }}

    steps:
      - name: Install BC Container Helper
        shell: pwsh   
        run: Install-Module bccontainerhelper -force

      - name: Check out the repository to the runner
        uses: actions/checkout@v4.2.1
        
      - name: Build Commits
        shell: pwsh       
        run: |
          ./scripts/Auto_load_versions.ps1 -country ${{matrix.countries}}
      
    
